### PR TITLE
Metadata fixes

### PR DESCRIPTION
**Pull request by sbesson**
Addresses various issues raised by @eleanorwilliams about the submission files

- moves generation scripts under `scripts` subfolder
- combines the 2 assays files into a single `idr0042-experimentA-assays.txt`
- only list `Diseases` and `Individual` under the study assay experimental conditions
- rename `Comment [Individual]` as `Characteristics [Individual]` and expose it in the maps 
- lowercase `Chronic heart failure`
- rename `Characteristics [Age in years]` as `Characteristics [Age]` and add the units to the rows
- modify the protocols section to have include treatment and imaging and reference them from the assays file

### CODE REVIEW

**Comment by sbesson** [comment]
Reannotated the dataset into the testing server and reloaded the cache - see

screen shot 2018-03-20 at 11 38 35

Should be ready for review.

**Comment by dominikl** [comment]
Generally looks good. Double checked a few map annotations with the original metadata, didn't see any mismatches. I just noticed that some images in the 'test' dataset are lacking annotations, although the submitted metadata file provide these, e.g. the third image in the dataset 33375_0_fal_23_0.png (id 3431541).

**Comment by sbesson** [comment]
Did use the 9000 port to make sure you are not testing previously cached data?

screen shot 2018-03-20 at 13 40 15

**Comment by dominikl** [comment]
You're right, caching issue. Looks fine! Only thing which I find a bit strange is that every map annotation value is lower case, except 'Ethnic or Racial Group', is that intended?

**Comment by sbesson** [comment]
Looking at the previous metadata files, we certainly tend to lowercase the values except when capitalization is mandatory like for gene names. In this case, I think racial and ethnic group are  meant to be capitalized like nationalities. Happy to get confirmation/disagreement from native speakers.

**Comment by sbesson** [comment]
Merging the above to make progress and I will work on the last round of comments by @eleanorwilliams in a separate PR.

**Pull request merged**
